// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Public fallback values (URL + anon key are public by design).
// Used when the bundler does not inject VITE_* vars (some published/share builds).
const FALLBACK_SUPABASE_URL = "https://qjmcozgprfprsqyyoppm.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqbWNvemdwcmZwcnNxeXlvcHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyODA4NzQsImV4cCI6MjA5Mzg1Njg3NH0.0bb_X1BABMg4EKpa0sS0okGS4ZeiwO4oR2t-cplQwVA";

function readEnv(key: string): string | undefined {
  try {
    const viteEnv = (import.meta as any)?.env;
    if (viteEnv && viteEnv[`VITE_${key}`]) return viteEnv[`VITE_${key}`];
  } catch {}
  try {
    if (typeof process !== "undefined" && (process as any).env?.[key]) {
      return (process as any).env[key];
    }
  } catch {}
  return undefined;
}

function createSupabaseClient() {
  const SUPABASE_URL = readEnv("SUPABASE_URL") || FALLBACK_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    readEnv("SUPABASE_PUBLISHABLE_KEY") || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
